#!/bin/bash

if [ "$1" == "" ] || [ "$1" == "con" ]; then
    action=connect
elif [ "$1" == "dis" ]; then
    action=disconnect
else
    action=$1
fi
sudo /opt/cisco/anyconnect/bin/vpn $action webvpn.fhcrc.org
