#!/usr/bin/env python
import sys
import argparse
import csv
import subprocess
import os

parser = argparse.ArgumentParser()
parser.add_argument('argnumbers', nargs='+')
args = parser.parse_args()

argstr = ','.join('$%d'%int(a) for a in args.argnumbers)
subprocess.check_call(['awk', '{print %s}'%argstr], stdin=sys.stdin)
