#!/usr/bin/env python
import sys
import subprocess
import os

if len(sys.argv) < 2:
    raise Exception('no arg number provided')
argnum = int(sys.argv[1])
subprocess.check_call(['awk', '{print $' + str(argnum) + '}'], stdin=sys.stdin)
