#!/usr/bin/env python
import argparse
import sys
import csv
csv.field_size_limit(sys.maxsize)  # make sure we can write very large csv fields

parser = argparse.ArgumentParser()
parser.add_argument('infname')
parser.add_argument('-c', '--columns', default='')
parser.add_argument('--lines', type=int)
parser.add_argument('--tab', action='store_true')  # tab delimiter
args = parser.parse_args()
if len(args.columns) > 0:
    args.columns = args.columns.split(':')

delimiter = ','
if args.tab or '.tsv' in args.infname:
    delimiter = '\t'

with open(args.infname) as infile:
    reader = csv.DictReader([row for row in infile if row[0]!='#'], delimiter=delimiter)
    columns_to_use = args.columns if len(args.columns) > 0 else reader.fieldnames
    if len(set(reader.fieldnames)) != len(reader.fieldnames):
        raise Exception('non-unique fieldnames, which won\'t work with csv.DictReader: %s' % [n for n in reader.fieldnames if reader.fieldnames.count(n) > 1])
    lvals, wstrs = [], [len(c) for c in columns_to_use]
    iline = 0
    for line in reader:
        vals = [line[col] for col in columns_to_use]
        lvals.append(vals)
        wstrs = [max(len('%s'%v), w) for v, w in zip(vals, wstrs)]
    wstrs = ['%'+str(w+2)+'s' for w in wstrs]
    for vals in lvals:
        val_strs = [(w % v) for v, w in zip(vals, wstrs)]

        if iline == 0:  # print header
            print(''.join([(w % h) for h, w in zip(columns_to_use, wstrs)]))
        print(''.join(val_strs))
        iline += 1
        if args.lines is not None and iline >= args.lines:
            break
