#!/usr/bin/env python
import sys
import os
import subprocess

clist = sys.argv[1:]
cmd = './bin/partis view-output'
if '--paired' in clist:
    clist.remove('--paired')
    cmd += ' --paired-loci --paired-outdir'
else:
    cmd += ' --outfname'
cmd += ' ' + ' '.join(clist)
print(cmd)
subprocess.check_call(cmd.split())
