#!/usr/bin/env python
# https://docs.python.org/2/library/profile.html#instant-user-s-manual
import pstats
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--infname', default='prof.out')
parser.add_argument('--lines', type=int, default=50)
args = parser.parse_args()

p = pstats.Stats(args.infname)
# p.strip_dirs().sort_stats(-1).print_stats()
# p.sort_stats('name')
# p.print_stats()
p.sort_stats('cumtime').print_stats(args.lines)  # tottime  # .reverse_order()
