#!/bin/bash

sign=$*

if [ "$sign" == "up" ]; then
    VOLUME='+5%'
elif [ "$sign" == "down" ]; then
    VOLUME='-5%'
else
    echo " sign must be either \"up\" or \"down\""
    exit 1
fi

if pactl -h &>/dev/null; then  # pre-24.04 uses pactl
    for SINK in $(pacmd list-sinks | grep 'index:' | cut -b12-)
    do
        pactl set-sink-volume $SINK $VOLUME
    done
else  # 24.04 uses wpctl (-l 1.5 limits final value to 150%)
    delta_str=`echo $VOLUME | sed 's/\([+-]\)\(.*\)/\2\1/'`  # move +/- from before to after value/percent sign
    wpctl set-volume @DEFAULT_AUDIO_SINK@ $delta_str
fi
