#!/bin/bash

sign=$*

if [ "$sign" == "up" ]; then
    VOLUME='+5%'
elif [ "$sign" == "down" ]; then
    VOLUME='-5%'
else
    echo " sign must be either \"up\" or \"down\""
    exit 1
fi

for SINK in $(pacmd list-sinks | grep 'index:' | cut -b12-)
do
    pactl set-sink-volume $SINK $VOLUME
done
