#!/bin/bash

sname=$1
if [ "$sname" == "" ]; then
    sname=partis
fi
sdir=$HOME/work/partis

if tmux has-session -t $sname; then
    echo "session $sname already already exists"
    exit 0
fi

tmux new-session -d -c $sdir -s $sname -n emacs
tmux send-keys -t $sname:emacs "emacs `cat ~/Dropbox/bin/partis-files.txt`" Enter
tmux new-window -t $sname -c $sdir -n shell
tmux send-keys -t $sname:shell "export HISTFILE=~/.history/$sname-shell" Enter
tmux send-keys -t $sname:shell "export HISTFILESIZE=10000" Enter
tmux send-keys -t $sname:shell "export PROMPT_COMMAND=\"history -a\"" Enter
# tmux send-keys -t $sname:shell ". hsleep &" Enter
# append to bash history: history -a
# append contents of bash history file to this terminal's history list (NOTE -c clears this terminal's history without saving it anywhere, so you'd probably actually want to do this somewhat differently): history -c; history -r
# tmux send-keys -t $sname:shell "history -w" Enter
tmux send-keys -t $sname:shell "export pies=\"python/*.py bin/*.py test/*.py projects/*.py\"" Enter
tmux send-keys -t $sname:shell "#git checkout main && git merge dev && git checkout dev && git push origin main" Enter
tmux send-keys -t $sname:shell "#grep -rn \".\" pies" Enter
# NOTE don't use this any more, use ~/Dropbox/bin/gd  old:   tmux send-keys -t $sname:shell "#git diff >~/Dropbox/wip.patch" Enter
tmux new-window -t $sname -c $sdir -ns0
tmux new-window -t $sname -c $sdir -ns1
tmux new-window -t $sname -c $sdir -ns2
tmux attach -t $sname:emacs
