#!/bin/bash

sname=$1
if [ "$sname" == "" ]; then
    sname=partis
fi
if tmux has-session -t $sname &>/dev/null; then
    echo "session $sname already already exists"
    exit 0
fi

sdir=$2
if [ "$sdir" == "" ]; then
    sdir=$HOME/work/$sname
    echo "sdir not set, so using $sdir"
fi

if [ ! -d "$sdir" ]; then
    echo "creating directory $sdir"
    mkdir -p "$sdir"
fi

tmux new-session -d -c $sdir -s $sname --name emacs
if [ -f ~/Dropbox/bin/$sname-files.txt ]; then
    files="`cat ~/Dropbox/bin/$sname-files.txt`"
fi
tmux send-keys -t $sname:emacs "emacs $files" Enter
tmux new-window -t $sname -c $sdir --name shell
tmux send-keys -t $sname:shell "export HISTFILE=~/.history/$sname-shell" Enter
tmux send-keys -t $sname:shell "export HISTFILESIZE=10000" Enter
tmux send-keys -t $sname:shell "export HISTCONTROL=ignoredups" Enter
tmux send-keys -t $sname:shell "export PROMPT_COMMAND=\"history -a\"" Enter  # this appends the current shell's history to HISTFILE, whereas 'history -r' appends HISTFILE contents to the current shell's history (i.e. run the latter when you start a new tmux session)
# tmux send-keys -t $sname:shell ". hsleep &" Enter
# append to bash history: history -a
# append contents of bash history file to this terminal's history list (NOTE -c clears this terminal's history without saving it anywhere, so you'd probably actually want to do this somewhat differently): history -c; history -r
# tmux send-keys -t $sname:shell "history -w" Enter
tmux send-keys -t $sname:shell "export pies=\"python/*.py bin/*.py test/*.py projects/*.py\"" Enter
tmux send-keys -t $sname:shell "#git checkout main && git merge dev && git checkout dev && git push origin main" Enter
tmux send-keys -t $sname:shell "#grep -rn \".\" pies" Enter
# NOTE don't use this any more, use ~/Dropbox/bin/gd  old:   tmux send-keys -t $sname:shell "#git diff >~/Dropbox/wip.patch" Enter
tmux new-window -t $sname -c $sdir --name s0
tmux new-window -t $sname -c $sdir --name s1
# tmux new-window -t $sname -c $sdir --name s2
tmux attach -t $sname:emacs
