#!/bin/bash

outdir="$HOME/Dropbox/hill/training/trainparse-plots"
mkdir -p "$outdir"

# 2021: work tracking started Apr 12
trainparse --start-date 2021-Apr-12 --stop-date 2021-Dec-31 --plotfile "$outdir/2021.jpg"

# 2022 onward: full year
for y in 2022 2023 2024 2025 2026; do
    trainparse --start-date $y-Jan-1 --stop-date $y-Dec-31 --plotfile "$outdir/$y.jpg"
done

# generate html viewer
cat > "$outdir/index.html" <<'HTMLEOF'
<html>
<head><title>trainparse plots</title></head>
<body style="margin: 0; padding: 20px; background: #fff; text-align: center;">
HTMLEOF

for y in 2021 2022 2023 2024 2025 2026; do
    if [ -f "$outdir/$y.jpg" ]; then
        echo "<h1>$y</h1><div><img src=\"$y.jpg\" style=\"max-width: 100%;\"></div>" >> "$outdir/index.html"
    fi
done

cat >> "$outdir/index.html" <<'HTMLEOF'
</body>
</html>
HTMLEOF

echo "wrote $outdir/index.html"
