#!/usr/bin/env python
import sys
import csv
import argparse
import os
from datetime import datetime, timedelta
import calendar
import colored_traceback.always
# import imp

import tutils

base_path = '%s/Dropbox/hill/training' % os.getenv('HOME')

# ----------------------------------------------------------------------------------------
def trfname(year):
    return '%s/%d/general.txt' % (base_path, year)

# ----------------------------------------------------------------------------------------
def parse_trfile(year):
    # ----------------------------------------------------------------------------------------
    def init_tfo(line):
        tfo = {}
        lstrs = line.split()
        try:
            day = int(lstrs[0])
        except:
            raise Exception('couldn\'t parse day from \'%s\'' % line)
        month = lstrs[1].capitalize() if len(lstrs) > 1 else None
        if month not in calendar.month_abbr:
            raise Exception('couldn\'t parse month from \'%s\'' % line)
        tfo['date'] = datetime(year=year, month=list(calendar.month_abbr).index(month), day=day)
        if len(lstrs) < 3:
            if tfo['date'].date() == datetime.today().date():
                return None  # skip today since it's probably not complete
            else:
                raise Exception('date line must be len at least 3 but got %d for line \'%s\'' % (len(lstrs), line))
        tfo['xo'] = lstrs[2]
        return tfo
    # ----------------------------------------------------------------------------------------
    def add_to_tfo(tfo, line):
        if tfo['date'].date() == datetime.today().date():  # skip today since it's probably not complete
            return
        if line[:2] != '  ':
            raise Exception('first two chars must be spaces but got \'%s\' in:\n%s' % (line[:2], line))
        lstrs = line.split()
        activity = lstrs[0]
        tfo[activity] = {}
        if activity == 'work':
            tfo[activity]['hours'] = tutils.parsetime(lstrs[1])
            if tfo[activity]['hours'] is None:
                print('    couldn\'t parse time for %s: \'%s\'' % (str(tfo['date']), line))
        else:
            tfo[activity]['line'] = line
    # ----------------------------------------------------------------------------------------
    trainfos = []
    print('      parsing %s' % trfname(year))
    with open(trfname(year)) as tfile:
        tfo = None
        for line in tfile:
            line = line.rstrip('\n')
            if line[0] != ' ':  # new day
                if tfo is not None and tfo['date'].date() != datetime.today().date():  # add the last day to <trainfos> (skip today since it's probably not complete)
                    trainfos.append(tfo)
                tfo = init_tfo(line)
            elif tfo is not None:  # skip lines if tfo is None (today's incomplete entry)
                add_to_tfo(tfo, line)
    return trainfos

# ----------------------------------------------------------------------------------------
def get_n_week_time(trainfos, actstr, n_weeks):
    # prev_time = datetime.now() - timedelta(weeks=n_weeks)
    dtnow = datetime.now() - timedelta(days=1)  # go back to yesterday, since presumably we haven't finished writing today yet
    target_date = dtnow - timedelta(weeks=n_weeks)
    n_nonzero_days, n_total_days, time_total, earliest_date = 0, 0, 0, None
    for tfo in reversed(trainfos):
        if tfo['date'] < target_date:
            break
        if earliest_date is None or tfo['date'] < earliest_date:
            earliest_date = tfo['date']
        n_total_days += 1
        if actstr not in tfo:
            continue
        n_nonzero_days += 1
        time_total += tfo[actstr]['hours']
    if earliest_date > target_date:
        print('  warning: earliest found date %s later than target date %s' % (str(earliest_date), str(target_date)))
    print('    %d hours of %s (%.1f per week) over %d days (%d non-zero) from %s %s to %s %s' % (time_total, actstr, time_total / n_weeks, n_total_days, n_nonzero_days, calendar.month_abbr[earliest_date.month], earliest_date.day, calendar.month_abbr[dtnow.month], dtnow.day))

# ----------------------------------------------------------------------------------------
def plot_acty(actstr):
    print('    plotting activity \'work\'')
    mfos = {'dates' : [], 'hours' : [], 'n_days' : []}
    for tfo in trainfos:
        if args.start_date is None:
            args.start_date = tfo['date']
        elif args.start_date > tfo['date']:
            continue
        if args.stop_date is not None and tfo['date'] > args.stop_date:
            break
        mfos['dates'].append(tfo['date'])
        hour_str = tfo.get(actstr, {'hours' : 0})['hours']
        if hour_str is None:
            raise Exception('None type hour str for %s' % tfo['date'])
        mfos['hours'].append(float(hour_str))
        mfos['n_days'].append((tfo['date'] - args.start_date).days)
    if len(mfos['dates']) == 0:
        raise Exception('no dates passing start date %s' % args.start_date)

    # validate that every calendar day has an entry
    for i in range(1, len(mfos['dates'])):
        gap = (mfos['dates'][i] - mfos['dates'][i-1]).days
        if gap != 1:
            raise Exception('missing %d day(s) between %s and %s' % (gap - 1, mfos['dates'][i-1].date(), mfos['dates'][i].date()))

    # detect vacation periods: in each streak of consecutive zero-hour days,
    # the first 2 are treated as a normal weekend; any beyond that are vacation
    vacation_dates = set()
    run_start = None
    for i, (dt, hrs) in enumerate(zip(mfos['dates'], mfos['hours'])):
        if hrs == 0:
            if run_start is None:
                run_start = i
        else:
            if run_start is not None:
                n_vac = (i - run_start) - 2
                if n_vac > 0:
                    for j in range(run_start + 2, i):
                        vacation_dates.add(mfos['dates'][j])
                    print('      %d vacation days in %d-day streak: %s - %s'
                          % (n_vac, i - run_start, mfos['dates'][run_start+2].date(), mfos['dates'][i-1].date()))
            run_start = None
    # handle run extending to end
    if run_start is not None:
        run_end = len(mfos['dates'])
        n_vac = (run_end - run_start) - 2
        if n_vac > 0:
            for j in range(run_start + 2, run_end):
                vacation_dates.add(mfos['dates'][j])

    n_non_vacation = len(mfos['dates']) - len(vacation_dates)
    total_hours = sum(h for d, h in zip(mfos['dates'], mfos['hours']) if d not in vacation_dates)
    avg_hrs_per_week = total_hours / n_non_vacation * 7 if n_non_vacation > 0 else 0
    print('    %.1f hrs/week average (%d vacation days excluded)' % (avg_hrs_per_week, len(vacation_dates)))

    tutils.add_float_averages(mfos, 'hours', args.half_window, debug=args.debug)
    tutils.add_float_averages(mfos, 'hours', args.weekly_half_window, output_key='weekly_avgs', exclude_dates=vacation_dates)
    mfos['weekly_avgs'] = [float('nan') if d in vacation_dates else v * 7 for d, v in zip(mfos['dates'], mfos['weekly_avgs'])]
    tutils.plot_mfos(args, mfos, 'hours', vacation_dates=vacation_dates, avg_hrs_per_week=avg_hrs_per_week)

# ----------------------------------------------------------------------------------------
helpstr="""
trainparse --debug --start-date 2021-Apr-15 --half-window 7
trainparse --start-date 2025-jan-1 --stop-date 2025-dec-31
"""
parser = argparse.ArgumentParser(description=helpstr)
# parser.add_argument('--mfile', default='%s/Dropbox/hill/m.csv' % os.getenv('HOME'))
# parser.add_argument('--plot', action='store_true')
parser.add_argument('--start-date', help='e.g. 2019-Jun-1 (note that the floating average can\'t see any values before this, i.e. the first few days will be only averaged over values on one side (the right)')
parser.add_argument('--stop-date', help='see --start-date')
parser.add_argument('--plotfile', default=os.getenv('HOME') + '/train.jpg', help='output jpg file name')
parser.add_argument('--half-window', type=float, default=3.5, help='half width of window for averaging weights')
parser.add_argument('--weekly-half-window', type=float, default=15, help='half width of window for weekly hours average (default 45.5 = ~3 months)')
parser.add_argument('--debug', action='store_true')
args = parser.parse_args()
tutils.process_args(args)

trainfos = []
for year in range(2021, datetime.now().year+1):
    trainfos += parse_trfile(year)  # NOTE assumes you have the years sequentially
# get_time_per_week(trainfos, 'work')
# get_n_week_time(trainfos, 'work', 3)
plot_acty('work')
