#!/bin/bash

# usage: tsv2fasta in.tsv out.fa 3 4
#   where 3 4 should be the name/seq column indices

infile=$1
if ! [ $infile ] || ! [ -f $infile ]; then
    echo "ERROR $infile d.n.e."
    exit 1
fi

outfile=$2
if [ "$outfile" == "" ]; then
    outfile=`echo $infile | sed 's/\.tsv/.fa/'`
fi

namecol=$3
if [ "$namecol" == "" ]; then
    namecol=1
fi

seqcol=$4
if [ "$seqcol" == "" ]; then
    seqcol=2
fi

grep -v sequence_id $infile | cut -d\t -f$namecol,$seqcol | column -t -s, | awk '{print ">",$1,"\n",$2}' | tr '\r' ' ' | sed 's/ //g' > $outfile
