#!/usr/bin/env python3
import sys
import math
from datetime import datetime

from tutils import parsetime

# usage: wtime "(730-18, -3:00)"
# NOTE won't work for unless second one is 24 hr time
debug = True

# tstr = ''.join(sys.argv[1:])
import subprocess
wline = subprocess.check_output('grep work ~/Dropbox/hill/training/%d/general.txt | tail -n1' % datetime.now().year, shell=True, universal_newlines=True)
assert wline.split()[0] == 'work'
tstr = ' '.join(wline.split()[1:]).strip()
tstr = tstr.strip('()')
if ',' in tstr:
    assert tstr.count(',') == 1
    bstr, minus_str = tstr.split(',')
    assert minus_str.strip()[0] == '-'
    minus_str = minus_str.strip().lstrip('-')
else:
    bstr = tstr
    minus_str = '0:00'
assert bstr.count('-') == 1
startstr, stopstr = bstr.split('-')

tstart = parsetime(startstr, debug=debug)
tstop = parsetime(stopstr, debug=debug)
tminus = parsetime(minus_str, debug=debug)

tot_time_float = tstop - tstart - tminus
tot_time_colon = '%d:%02d' % (math.floor(tot_time_float), int(60 * (tot_time_float - math.floor(tot_time_float))))
if debug:
    print('(%.2f - %.2f) - %.2f = %.2f --> %s' % (tstop, tstart, tminus, tot_time_float, tot_time_colon))
print(tot_time_colon)
