#!/bin/bash

cfgdir=~/.config/xmodmap

cfgstr=$1
if [ "$cfgstr" != "" ]; then
    cfgfn=$cfgdir/`hostname`-$cfgstr.cfg
else
    cfgfn=$cfgdir/`hostname`.cfg
fi

echo "executing xmodmap $cfgfn on `date`"
xmodmap $cfgfn
